version: "3.8"

services:
  # Shared reverse proxy
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - nginx_certs:/etc/nginx/certs:ro
      - nginx_vhost:/etc/nginx/vhost.d
      - nginx_html:/usr/share/nginx/html
    networks:
      - proxy_net

  # Let's Encrypt HTTPS companion
  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-letsencrypt
    restart: always
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - nginx_certs:/etc/nginx/certs
      - nginx_vhost:/etc/nginx/vhost.d
      - nginx_html:/usr/share/nginx/html
    depends_on:
      - nginx-proxy
    networks:
      - proxy_net

  # JupyterLab container
  jupyter:
    build: .
    container_name: jupyter
    restart: unless-stopped
    expose:
      - "8888"
    env_file:
      - .env
    volumes:
      - ./notebooks:/app/notebooks
    networks:
      - proxy_net

volumes:
  nginx_certs:
  nginx_vhost:
  nginx_html:

networks:
  proxy_net:
    driver: bridge
